name: Acebook CI workflow

on: 
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 23
    
    - name: Install dependencies
      run: npm install

    - name: Start the server
      run: npm run start:test &

    - name: Wait for test server
      run: npx wait-on http://localhost:3030

    - name: Run tests
      run: npm test
